# fly.toml app configuration file generated for people1-history on 2024-10-17T14:30:48+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'people1-history'
primary_region = 'nrt'

[processes]
  web = "bin/rails server"
  cron = "supercronic /rails/crontab"

[build]
  dockerfile = './Dockerfile'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["web"]

[[statics]]
  guest_path = "/rails/public"
  url_prefix = "/"

[[vm]]
  size = 'shared-cpu-1x'
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1
  processes = ['cron', 'web']